/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   project-details-editor.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

declare namespace UiElements {

  /**
   * An element to render project details editor.
   */
  class ProjectDetailsEditor extends PolymerElement {

    /**
     * Name of the project.
     */
    name: string|null|undefined;

    /**
     * The description of the project
     */
    description: string|null|undefined;

    /**
     * Sends the `cancel-edit` custom event to the parent element.
     */
    cancel(): void;

    /**
     * Sends the `save-edit` custom event to the parent element.
     */
    save(): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "project-details-editor": UiElements.ProjectDetailsEditor;
  }
}

export {};
